/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_salarie;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class EtatVehicule extends javax.swing.JFrame {

    /**
     * Creates new form EtatVehicule
     */
    public EtatVehicule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        N_immatriculationfield = new javax.swing.JTextField();
        marqueField = new javax.swing.JTextField();
        modeleField = new javax.swing.JTextField();
        couleurField = new javax.swing.JTextField();
        ajouterbutton = new javax.swing.JButton();
        modifierUtilisateurbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        IDutilisateurField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TypeField = new javax.swing.JComboBox<>();
        historiquebutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        date_utilisation = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Etat des véhicules");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("N° d'immatriculation :");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("Marque :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Modéle :");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("Couleur :");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 30));
        getContentPane().add(N_immatriculationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 190, 30));

        marqueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marqueFieldActionPerformed(evt);
            }
        });
        getContentPane().add(marqueField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 190, 30));
        getContentPane().add(modeleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 190, 30));

        couleurField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couleurFieldActionPerformed(evt);
            }
        });
        getContentPane().add(couleurField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 190, 30));

        ajouterbutton.setBackground(new java.awt.Color(102, 102, 102));
        ajouterbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ajouterbutton.setText("Ajouter véhicule  ");
        ajouterbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ajouterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(ajouterbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, 40));

        modifierUtilisateurbutton.setBackground(new java.awt.Color(102, 102, 102));
        modifierUtilisateurbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifierUtilisateurbutton.setText("Modifier Utilisateur");
        modifierUtilisateurbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modifierUtilisateurbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierUtilisateurbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(modifierUtilisateurbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 140, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° d'immatriculation", "Type", "Marque", "Modéle", "Couleur", "Utilisateur", "Date utilisation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(55);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(55);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(45);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 0, 550, 480));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setText("ID Utilisateur :");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 170, 30));
        getContentPane().add(IDutilisateurField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel7.setText("type :");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 170, 30));

        TypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Voiture", "Camion benne", "Camion fourgon" }));
        TypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, 30));

        historiquebutton.setBackground(new java.awt.Color(102, 102, 102));
        historiquebutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        historiquebutton.setText("Historique");
        historiquebutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        historiquebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiquebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(historiquebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, 40));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setText("Date d'utilisation");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 30));
        getContentPane().add(date_utilisation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 190, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_salarie/steel_background_use_now_1000x500.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marqueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marqueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marqueFieldActionPerformed

    private void couleurFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couleurFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_couleurFieldActionPerformed

    private void modifierUtilisateurbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierUtilisateurbuttonActionPerformed
        PreparedStatement prs;
        ResultSet rst;
        Connectiondb connect=new Connectiondb();
        String nImmatriculation=N_immatriculationfield.getText();
        String IDutilisateur=IDutilisateurField.getText();
        String date_util="";
        
        String query="INSERT INTO `vehicule_utilisation` (`ID_salarie`, `N_immatriculation`, `ID_date`) VALUES (?,?,?);";
        
        try {
            if(date_utilisation.getDate()!=null && !"".equals(IDutilisateur)){
           SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
           date_util=date.format(date_utilisation.getDate());
           String query2="INSERT INTO `date` (`date_debut`) VALUES (?)";
           prs=connect.connectdb().prepareStatement(query2);
           prs.setString(1, date_util);
           prs.executeUpdate();
           
           String query4="SELECT ID_Date FROM date WHERE date_debut=?";
           prs=connect.connectdb().prepareStatement(query4);
           prs.setString(1, date_util);
           rst=prs.executeQuery();
           String id_date="";
            if(rst.next())
             {
                 id_date=rst.getString(1);
             }
            
            prs=connect.connectdb().prepareStatement(query);
            prs.setString(1, IDutilisateur);
            prs.setString(2, nImmatriculation);
            prs.setString(3, id_date);
            if(prs.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Modification appliquer","succés",JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Erruer vehicule ou salarie n'exist pas !!!!","Erreur",JOptionPane.WARNING_MESSAGE);
            }
         }
            else{
                JOptionPane.showMessageDialog(rootPane, "vous devez remplir la date et ID d'utilisateur !!!","Erreur",JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EtatVehicule.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erruer vehicule ou salarie n'exist pas !!!!","Erreur",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_modifierUtilisateurbuttonActionPerformed

    private void TypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeFieldActionPerformed

    private void ajouterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterbuttonActionPerformed
        PreparedStatement prs;
        ResultSet rst;
        Connectiondb connect=new Connectiondb();
        String nImmatriculation=N_immatriculationfield.getText();
        String type=TypeField.getSelectedItem().toString();
        String marque=marqueField.getText();
        String modele=modeleField.getText();
        String couleur=couleurField.getText();
        //String IDutilisateur=IDutilisateurField.getText();
        
        String query="INSERT INTO `vehicule`(`n_imatriculation`, `type`, `marque`, `modéle`, `couleur`) VALUES (?,?,?,?,?)";
        if(nImmatriculation.equals("") || type.equals("" ) || marque.equals("") || modele.equals("") || couleur.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "un ou des champs importantes sont vides !!","Erreur",JOptionPane.WARNING_MESSAGE);
            
        }
        else {
            try {
            prs=connect.connectdb().prepareStatement(query);
            prs.setString(1, nImmatriculation);
            prs.setString(2, type);
            prs.setString(3, marque);
            prs.setString(4, modele);
            prs.setString(5, couleur);
            prs.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, type+" est ajouter", "succés", JOptionPane.INFORMATION_MESSAGE);
          } catch (SQLException ex) {
            Logger.getLogger(EtatVehicule.class.getName()).log(Level.SEVERE, null, ex);
          }
        }
        
    }//GEN-LAST:event_ajouterbuttonActionPerformed

    private void historiquebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiquebuttonActionPerformed
        PreparedStatement prs;
        ResultSet rst;
        Connectiondb connect=new Connectiondb();
        String nImmatriculation=N_immatriculationfield.getText();
        
        String query="SELECT N_immatriculation,type,marque,modéle,couleur,prenom,nom,date.date_debut FROM vehicule_utilisation,vehicule,salarie,date WHERE salarie.ID_salarie=vehicule_utilisation.ID_salarie AND vehicule_utilisation.N_immatriculation=vehicule.n_imatriculation AND date.ID_Date=vehicule_utilisation.ID_date AND N_immatriculation=?;";
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
         try {
            prs=connect.connectdb().prepareStatement(query);
            prs.setString(1, nImmatriculation);
            rst=prs.executeQuery();
            DefaultTableModel tableMd=(DefaultTableModel)jTable1.getModel();
            Object[] row;

            while(rst.next()){
                row=new Object[7];
                row[0]=rst.getInt(1);
                row[1]=rst.getString(2);
                row[2]=rst.getString(3);
                row[3]=rst.getString(4);
                row[4]=rst.getString(5);
                row[5]=rst.getString(6)+" "+rst.getString(7);
                row[6]=rst.getDate(8);
                tableMd.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificationSalarie.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_historiquebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtatVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtatVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtatVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtatVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtatVehicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDutilisateurField;
    private javax.swing.JTextField N_immatriculationfield;
    private javax.swing.JComboBox<String> TypeField;
    private javax.swing.JButton ajouterbutton;
    private javax.swing.JTextField couleurField;
    private com.toedter.calendar.JDateChooser date_utilisation;
    private javax.swing.JButton historiquebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField marqueField;
    private javax.swing.JTextField modeleField;
    private javax.swing.JButton modifierUtilisateurbutton;
    // End of variables declaration//GEN-END:variables
}
