/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_salarie;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class ModificationSalarie extends javax.swing.JFrame {

    /**
     * Creates new form ModificationSalarie
     */
    public ModificationSalarie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IDSalarieText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PrenomField = new javax.swing.JTextField();
        NomField = new javax.swing.JTextField();
        CINField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        AdresseField = new javax.swing.JTextField();
        NTelephoneField = new javax.swing.JTextField();
        Ajouterbutton = new javax.swing.JButton();
        Modifierbutton = new javax.swing.JButton();
        Rechercherbutton = new javax.swing.JButton();
        FonctionField = new javax.swing.JTextField();
        Supprimerbutton = new javax.swing.JButton();
        AffTSalariesbutton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        hommebutton = new javax.swing.JRadioButton();
        femmebutton = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modification de salariés");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        ID.setText("ID de salarié :");
        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 100, 28));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 980, 10));

        IDSalarieText.setBackground(new java.awt.Color(204, 204, 204));
        IDSalarieText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDSalarieTextActionPerformed(evt);
            }
        });
        jPanel1.add(IDSalarieText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 420, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("Nom :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Genre : ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("Prenom :");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 70, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("CIN :");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 70, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("Fonction :");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 80, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setText("Email :");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 130, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setText("Adresse :");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 130, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel9.setText("N° téléphone :");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 130, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel10.setText("Date d'embauche :");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 130, 30));

        PrenomField.setBackground(new java.awt.Color(204, 204, 204));
        PrenomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PrenomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, 30));

        NomField.setBackground(new java.awt.Color(204, 204, 204));
        NomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 180, 30));

        CINField.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(CINField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 180, 30));

        EmailField.setBackground(new java.awt.Color(204, 204, 204));
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 240, 30));
        EmailField.getAccessibleContext().setAccessibleDescription("");

        AdresseField.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(AdresseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 240, 30));

        NTelephoneField.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(NTelephoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 240, 30));

        Ajouterbutton.setBackground(new java.awt.Color(102, 102, 102));
        Ajouterbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ajouterbutton.setForeground(new java.awt.Color(255, 255, 255));
        Ajouterbutton.setText("Ajouter");
        Ajouterbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ajouterbutton.setMaximumSize(new java.awt.Dimension(80, 22));
        Ajouterbutton.setMinimumSize(new java.awt.Dimension(80, 22));
        Ajouterbutton.setPreferredSize(new java.awt.Dimension(80, 22));
        Ajouterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Ajouterbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 100, 40));

        Modifierbutton.setBackground(new java.awt.Color(102, 102, 102));
        Modifierbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Modifierbutton.setForeground(new java.awt.Color(255, 255, 255));
        Modifierbutton.setText("Modifier");
        Modifierbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Modifierbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Modifierbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 100, 40));

        Rechercherbutton.setBackground(new java.awt.Color(102, 102, 102));
        Rechercherbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Rechercherbutton.setForeground(new java.awt.Color(255, 255, 255));
        Rechercherbutton.setText("Rechercher");
        Rechercherbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Rechercherbutton.setPreferredSize(new java.awt.Dimension(80, 22));
        Rechercherbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Rechercherbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 110, 40));

        FonctionField.setBackground(new java.awt.Color(204, 204, 204));
        FonctionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FonctionFieldActionPerformed(evt);
            }
        });
        jPanel1.add(FonctionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 270, 30));

        Supprimerbutton.setBackground(new java.awt.Color(102, 102, 102));
        Supprimerbutton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Supprimerbutton.setForeground(new java.awt.Color(255, 255, 255));
        Supprimerbutton.setText("supprimer");
        Supprimerbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Supprimerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Supprimerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 100, 40));

        AffTSalariesbutton.setBackground(new java.awt.Color(102, 102, 102));
        AffTSalariesbutton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        AffTSalariesbutton.setForeground(new java.awt.Color(255, 255, 255));
        AffTSalariesbutton.setText("Afficher tous les salariés");
        AffTSalariesbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AffTSalariesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffTSalariesbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(AffTSalariesbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 180, 40));

        jDateChooser1.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDateChooser1.setDateFormatString("y MMM d");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 240, 30));

        buttonGroup1.add(hommebutton);
        hommebutton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        hommebutton.setText("Homme");
        hommebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hommebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(hommebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 80, -1));

        buttonGroup1.add(femmebutton);
        femmebutton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        femmebutton.setText("Femme");
        femmebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femmebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(femmebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 240, 80, -1));

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("*Champ Email n'est pas necessaire pour remplire.");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 270, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_salarie/steel_background_use_now_1000x500.jpg"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
   
    private void AjouterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterbuttonActionPerformed
         String Prenom=PrenomField.getText();
         String Nom=NomField.getText();
         String Genre=genre;
         String CIN=CINField.getText();
         String Adresse=AdresseField.getText();
         String NTelephone=NTelephoneField.getText();
         String DateEmbauche ="";
        if (jDateChooser1.getDate()!= null){
            SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
            DateEmbauche=date.format(jDateChooser1.getDate());
        }
         
         String Email=EmailField.getText();
         String Fonction=FonctionField.getText();
        
         if(NTelephone.equals("")|| Prenom.equals("")|| Nom.equals("")|| Genre.equals("")|| CIN.equals("") || Adresse.equals("")||DateEmbauche.equals("") ||Fonction.equals(""))
         {
             JOptionPane.showMessageDialog(rootPane, "un ou des champs importantes sont vides","Erreur!!",2);
         }
         else {
             Connectiondb connect=new Connectiondb();
             PreparedStatement prs;
             ResultSet rst;
             String query="INSERT INTO `salarie` (`prenom`, `nom`, `genre`, `CIN`, `adresse`, `n_telephone`,`date_embauche`, `email`, `fonction`) VALUES (?,?,?,?,?,?,?,?,?)";
             try {
                 prs=connect.connectdb().prepareStatement(query);
                 prs.setString(1, Prenom);
                 prs.setString(2, Nom);
                 prs.setString(3, Genre);
                 prs.setString(4, CIN);
                 prs.setString(5, Adresse);
                 prs.setString(6, NTelephone);
                 prs.setString(7, DateEmbauche);
                 prs.setString(8, Email);
                 prs.setString(9, Fonction);
                 
                 
                 if(prs.executeUpdate() > 0){
                     JOptionPane.showMessageDialog(rootPane, "Salarié Ajouter","succés",JOptionPane.INFORMATION_MESSAGE);
                 }
                 else{
                     JOptionPane.showMessageDialog(rootPane, "Erreur salarié non Ajouter","Erreur!!",2);
                 }
                 
             } catch (SQLException ex) {
                 Logger.getLogger(ModificationSalarie.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(rootPane, "Erreur salarié non Ajouter","Erreur!!",2);
             }
             
         }
         
    }//GEN-LAST:event_AjouterbuttonActionPerformed

    private void NomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomFieldActionPerformed

    private void PrenomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void FonctionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FonctionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FonctionFieldActionPerformed

    public void AFFToustable(JTable table){
        PreparedStatement prs;
        ResultSet rst;
        Connectiondb connect=new Connectiondb();
        
        String query="SELECT * FROM `salarie`";
        try {
            prs=connect.connectdb().prepareStatement(query);
            rst=prs.executeQuery();
            DefaultTableModel tableMd=(DefaultTableModel)table.getModel();
            Object[] row;

            while(rst.next()){
                row=new Object[10];
                row[0]=rst.getInt(1);
                row[1]=rst.getString(3);
                row[2]=rst.getString(4);
                row[3]=rst.getString(5);
                row[4]=rst.getString(6);
                row[5]=rst.getString(7);
                row[6]=rst.getString(8);
                row[7]=rst.getDate(9);
                row[8]=rst.getString(10);
                row[9]=rst.getString(11);
                
                tableMd.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificationSalarie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
              
    private void AffTSalariesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffTSalariesbuttonActionPerformed
       //Afficher tous salariés       --------------------
       
        TableTousS tabtous=new TableTousS();
        tabtous.setVisible(true);
        tabtous.pack();
        tabtous.setLocationRelativeTo(null);
        tabtous.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    }//GEN-LAST:event_AffTSalariesbuttonActionPerformed

    private void hommebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hommebuttonActionPerformed
         genre="homme";
    }//GEN-LAST:event_hommebuttonActionPerformed

    private void femmebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femmebuttonActionPerformed
        genre="femme";
    }//GEN-LAST:event_femmebuttonActionPerformed

    private void ModifierbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierbuttonActionPerformed
        PreparedStatement prs;
        ResultSet rst;
        Connectiondb connect=new Connectiondb();
        String ID=IDSalarieText.getText();
        
        String Prenom=PrenomField.getText();
        String Nom=NomField.getText();
        String Genre=genre;
        String CIN=CINField.getText();
        String Adresse=AdresseField.getText();
        String NTelephone=NTelephoneField.getText();
        String DateEmbauche ="";
        if (jDateChooser1.getDate()!= null){
            SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
            DateEmbauche=date.format(jDateChooser1.getDate());
        }
         
        String Email=EmailField.getText();
        String Fonction=FonctionField.getText();
   if(NTelephone.equals("")|| Prenom.equals("")|| Nom.equals("")|| Genre.equals("")|| CIN.equals("") || Adresse.equals("")||DateEmbauche.equals("") ||Fonction.equals(""))
    {
             JOptionPane.showMessageDialog(rootPane, "un ou des champs importantes sont vides","Erreur!!",2);
    }
  else{
        
        String query="UPDATE `salarie` SET `prenom`=?,`nom`=?,`genre`=?,`CIN`=?,`adresse`=?,`n_telephone`=?,`date_embauche`=?,`email`=?,`fonction`=? WHERE ID_salarie=?";
        try {
            prs=connect.connectdb().prepareStatement(query);
            prs.setString(1,Prenom);
            prs.setString(2,Nom);
            prs.setString(3,Genre);
            prs.setString(4,CIN);
            prs.setString(5,Adresse);
            prs.setString(6,NTelephone);
            prs.setString(7,DateEmbauche);
            prs.setString(8,Email);
            prs.setString(9,Fonction);
            
            prs.setString(10, ID);
            
            prs.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(ModificationSalarie.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(rootPane, "Salarié Modifier","succés",JOptionPane.INFORMATION_MESSAGE);
      }   
    }//GEN-LAST:event_ModifierbuttonActionPerformed

    private void SupprimerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerbuttonActionPerformed
        PreparedStatement prs;
        ResultSet rst;
        Connectiondb connect=new Connectiondb();
        
        String ID_sal=IDSalarieText.getText();
        int option=JOptionPane.showConfirmDialog(null, "êtes-vous sûr de supprimer ce salarier ?", "confirmer supression",JOptionPane.YES_NO_OPTION);
        String query="DELETE FROM `salarie` WHERE ID_salarie=?";
        if (option==0)
        {
             try {
                   prs=connect.connectdb().prepareStatement(query);
                   prs.setString(1, ID_sal);
                   prs.executeUpdate();
            
             } catch (SQLException ex) {
                   Logger.getLogger(ModificationSalarie.class.getName()).log(Level.SEVERE, null, ex);
             }
          JOptionPane.showMessageDialog(rootPane, "Salarié supprimer","succés",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SupprimerbuttonActionPerformed

    private void RechercherbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherbuttonActionPerformed
        PreparedStatement prs;
        ResultSet rst;
        Connectiondb connect=new Connectiondb();
        
        String id_rechercher=IDSalarieText.getText();
        String query="SELECT * FROM salarie WHERE ID_salarie=?";
        
        try {
            prs=connect.connectdb().prepareStatement(query);
            prs.setString(1, id_rechercher);
            rst=prs.executeQuery();
            
            if(rst.next()) // cad si salarie existe
            {
              
                    IDSalarieText.setText(rst.getString(1));
                    PrenomField.setText(rst.getString(3));
                    NomField.setText(rst.getString(4));
                    String Genrecheck=rst.getString(5);
                    if (Genrecheck.equals("homme"))
                    {
                        hommebutton.setSelected(true);
                    }
                    else femmebutton.setSelected(true);
                    CINField.setText(rst.getString(6));
                    AdresseField.setText(rst.getString(7));
                    NTelephoneField.setText(rst.getString(8));
                    jDateChooser1.setDate(rst.getDate(9));
                    EmailField.setText(rst.getString(10));
                    FonctionField.setText(rst.getString(11));
                
            }
            else{
               JOptionPane.showMessageDialog(rootPane, "Ce salarié n'existe pas !!","Erreur",JOptionPane.ERROR_MESSAGE);

            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificationSalarie.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }//GEN-LAST:event_RechercherbuttonActionPerformed

    private void IDSalarieTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDSalarieTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDSalarieTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificationSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificationSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificationSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificationSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificationSalarie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresseField;
    private javax.swing.JButton AffTSalariesbutton;
    private javax.swing.JButton Ajouterbutton;
    private javax.swing.JTextField CINField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField FonctionField;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDSalarieText;
    private javax.swing.JButton Modifierbutton;
    private javax.swing.JTextField NTelephoneField;
    private javax.swing.JTextField NomField;
    private javax.swing.JTextField PrenomField;
    private javax.swing.JButton Rechercherbutton;
    private javax.swing.JButton Supprimerbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femmebutton;
    private javax.swing.JRadioButton hommebutton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
 private String genre;
}
