/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_salarie;

import javax.swing.JFrame;

/**
 *
 * @author Lenovo
 */
public class page_initiale extends javax.swing.JFrame {

    /**
     * Creates new form page_initiale
     */
    public page_initiale() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modificationSalarie = new javax.swing.JButton();
        disponibilite = new javax.swing.JButton();
        EtatVehicule = new javax.swing.JButton();
        sortir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Page Initiale");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificationSalarie.setBackground(new java.awt.Color(204, 255, 255));
        modificationSalarie.setForeground(new java.awt.Color(0, 0, 102));
        modificationSalarie.setText("Modification de salariés");
        modificationSalarie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificationSalarie.setPreferredSize(new java.awt.Dimension(75, 25));
        modificationSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationSalarieActionPerformed(evt);
            }
        });
        jPanel1.add(modificationSalarie, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 210, 30));

        disponibilite.setBackground(new java.awt.Color(204, 255, 255));
        disponibilite.setForeground(new java.awt.Color(0, 0, 102));
        disponibilite.setText("Disponibilité de salariés");
        disponibilite.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        disponibilite.setPreferredSize(new java.awt.Dimension(75, 25));
        disponibilite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponibiliteActionPerformed(evt);
            }
        });
        jPanel1.add(disponibilite, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 210, 30));

        EtatVehicule.setBackground(new java.awt.Color(204, 255, 255));
        EtatVehicule.setForeground(new java.awt.Color(0, 0, 102));
        EtatVehicule.setText("Etat des Véhicules");
        EtatVehicule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EtatVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtatVehiculeActionPerformed(evt);
            }
        });
        jPanel1.add(EtatVehicule, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, 30));

        sortir.setBackground(new java.awt.Color(204, 255, 255));
        sortir.setForeground(new java.awt.Color(0, 0, 102));
        sortir.setText("Sortir");
        sortir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortirActionPerformed(evt);
            }
        });
        jPanel1.add(sortir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_salarie/employe_management_2_1000x475.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("page  initiale");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modificationSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificationSalarieActionPerformed
          ModificationSalarie modifsalarie =new ModificationSalarie();
          modifsalarie.setVisible(true);
          modifsalarie.pack();
          modifsalarie.setLocationRelativeTo(null);
          modifsalarie.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_modificationSalarieActionPerformed

    private void sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortirActionPerformed
        this.dispose();
    }//GEN-LAST:event_sortirActionPerformed

    private void disponibiliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponibiliteActionPerformed
          DisponibiliteSalarie disposalarie =new DisponibiliteSalarie();
          disposalarie.setVisible(true);
          disposalarie.pack();
          disposalarie.setLocationRelativeTo(null);
          disposalarie.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_disponibiliteActionPerformed

    private void EtatVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtatVehiculeActionPerformed
          EtatVehicule vehicule =new EtatVehicule();
          vehicule.setVisible(true);
          vehicule.pack();
          vehicule.setLocationRelativeTo(null);
          vehicule.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_EtatVehiculeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page_initiale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page_initiale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EtatVehicule;
    private javax.swing.JButton disponibilite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificationSalarie;
    private javax.swing.JButton sortir;
    // End of variables declaration//GEN-END:variables
}
